### ISSUE TITLE
[BUG] JobServerFilter.onProcessed() doesn't work as expected

### ISSUE THREAD

**Issue by jhchee** [jobrunr/jobrunr#696] opened 2023-02-19 10:58 UTC
### JobRunr Version

6.0.0

### JDK Version

Java 17

### Your SQL / NoSQL database

Postgres 14.6

### What happened?

JobServerFilter.onProcessed() is having unexpected behavior:
1. It doesn't intercept SUCCEEDED state.
2. It intercepts PROCESSING state twice (shown in the log below).

### How to reproduce?

Job class
```java
@Component
@Slf4j
public class DemoJobs implements JobI {
      @Job(jobFilters = {NotifyJobProcessedFilter.class})
      @Recurring(cron = "*/10 * * * * *")
      @Override
      public void execute() throws Exception {
          log.info("executed");
      }
}
```
JobServerFilter implementation
```java
@Slf4j
public class NotifyJobProcessedFilter implements JobServerFilter {
    @Override
    public void onProcessed(Job job) {
        System.out.println(job.getJobState().getName().name());
    }
}
```

Project link: https://github.com/jhchee/jobrunr-demo

### Relevant log output

```shell
2023-02-19T18:53:26.647+08:00  INFO 24019 --- [pool-2-thread-6] j.github.jobrunrdemo.jobs.DemoJobs       : executed
PROCESSING
PROCESSING
```
```

**Comment by rdehuyss** [comment] 2023-02-19 11:30
Normally I would close this issue due to not following community guidelines.

When creating the issue, it clearly states **NOT** to assign somebody to the issue. I also don't tell you what work to pick up.

**Comment by jhchee** [comment] 2023-02-19 11:33
@rdehuyss Hey I didn't assign anyone to this ticket. This is all handled by the PR template. You can try reproduce it.

**Comment by jhchee** [comment] 2023-02-19 11:35
@rdehuyss I try it once again, you have set yourself as the default assignee, there is no way I can unassign this.

**Comment by rdehuyss** [comment] 2023-02-19 11:39
@jhchee - really? Thanks for mentioning that! Sorry for the remark - I'll need to investigate the issue template.

By the way - this is expected behaviour: you're seeing it twice due to the fact that your CRON job is running every 10 seconds so you'll have multiple jobs which have successfully been processed. 

If the method is invoked, it means your job has successfully processed but it is still in the `PROCESSING` state.

I think you are looking for the `ApplyStateFilter` where you can perform logic if the job succeeded based on the `newState` argument.

**Closed by rdehuyss** 2023-02-19 11:39 UTC

**Comment by jhchee** [comment] 2023-02-19 11:43
I was going through this [documentation](https://www.jobrunr.io/en/documentation/pro/job-filters/). By your comment, the example shown in the documentation shouldn't be working as it will never run into SUCCEEDED or FAILED.

**Comment by rdehuyss** [comment] 2023-02-19 11:47
Completely correct again - I'll make sure to update that example.

**Comment by rdehuyss** [comment] 2023-02-19 12:02
In fact, I'll improve the API to add the following default methods: `onSuccess`, `onFailure`, `onFailureAfterRetries`.

I think that makes more sense and is developer-friendlier.

**Comment by rdehuyss** [comment] 2023-02-20 07:53
Will be solved in next release of JobRunr. Please star the repo if you're happy with the quick resolution time!
