### ISSUE TITLE
[BUG] Recurring jobs with same job details and UNIQUE id are considered one job!

### ISSUE THREAD

**Issue by alaamalas** [jobrunr/jobrunr#54] opened 2020-10-22 11:47 UTC
I am using JobRunr to create multiple recurring jobs to fetch all user's data every 10 min, using same method and just changing the user id, and of course, I provide a unique id for each recurring job based on user id.
But jobrunr seems to ignore the provided job id, and it considers all jobs as one job because they have the same method name and type.

```
jobScheduler.scheduleRecurrently("One",() -> System.out.println("One"), Cron.minutely());
jobScheduler.scheduleRecurrently("Two", () -> System.out.println("Two"), Cron.minutely());
```
Different recurring jobs get added successfully:
![image](https://user-images.githubusercontent.com/66674784/96858304-c178b600-1468-11eb-92f6-4ac10c4c98d1.png)

But only executes the job with id = "Two" over and over  :
![image](https://user-images.githubusercontent.com/66674784/96858922-8c209800-1469-11eb-9676-7faedea50e83.png)

A step further, I changed the called printing method for the job with id = "One" ;
from print("One") to println("Two"),  and repeated the test, 
after this change jobrunr was able to run both jobs recurrently because the job method was changed 

```
jobScheduler.scheduleRecurrently("One",() -> System.out.print("One"), Cron.minutely());
jobScheduler.scheduleRecurrently("Two", () -> System.out.println("Two"), Cron.minutely());
```

![image](https://user-images.githubusercontent.com/66674784/96859707-7d86b080-146a-11eb-8a77-1b2bf28a5351.png)

![image](https://user-images.githubusercontent.com/66674784/96867053-e5da8f80-1474-11eb-8344-18558933d80b.png)

**Comment by rdehuyss** [comment] 2020-10-22 14:57
Hi @alaamalas ,

I think you are still running v1.0.1. A bug has already been submitted for this issue and so I think this is a duplicate of #43 .

Could you please upgrade to v1.1.0, try again and report back?

Thanks!

**Comment by alaamalas** [comment] 2020-10-25 07:04
Hi @rdehuyss 

I have upgraded to  v1.1.1, and the bug is fixed and verified.

Thanks a lot

**Closed** 2020-10-25 07:05 UTC
Labels: Awaiting feedback, bug, duplicate
