### ISSUE TITLE
[BUG] Not all reccurent scheduled job are being triggered

### ISSUE THREAD

**Issue by goldencubegames** [jobrunr/jobrunr#535] opened 2022-08-09 15:31 UTC
**Are you running the latest version of JobRunr?**
No, newest version does not work
If no, please first upgrade to the latest JobRunr version and check whether the issue still exists.

**Describe the bug**
Not all reccurent scheduled job are being triggered
Job should be triggered once per hour

Triggered:
2022.08.07 01:00:37.848
2022.08.07 02:00:31.189
2022.08.07 03:00:43.375
2022.08.07 04:00:42.226
2022.08.07 05:00:40.298
2022.08.07 06:00:35.163
2022.08.07 07:00:42.207
2022.08.07 08:00:36.551
2022.08.07 09:00:37.885
2022.08.07 10:00:32.866
2022.08.07 11:00:39.742
2022.08.07 12:00:43.539
2022.08.07 13:00:34.673
2022.08.07 14:00:38.833
2022.08.07 15:00:40.862
2022.08.07 16:00:33.793
2022.08.07 17:00:40.589
2022.08.07 18:00:42.664
2022.08.07 20:00:30.150
2022.08.07 22:00:33.321
2022.08.07 23:00:37.855

Didn´t trigger:
2022.08.07 00:00
2022.08.07 19:00
2022.08.07 21:00

Environment
I'm using JobRunr version: 5.0.1
I'm running on JRE / JDK openjdk:11.0-jdk
I'm using the following StorageProvider MongoDB

**Expected behavior**
Job should be triggered once per hour

**Comment by rdehuyss** [comment] 2022-08-09 15:54
Duplicate of #448

**Closed by rdehuyss** 2022-08-09 15:54 UTC

**Comment by goldencubegames** [comment] 2022-08-09 16:50
after upgrading to 5.0.2-RC none of the jobs are executed, all stuck in enqueue state

**Comment by rdehuyss** [comment] 2022-08-09 17:27
There are several testbeds running without problem currently. Could you setup a repo that reproduces the issue?

**Comment by rdehuyss** [comment] 2022-08-09 19:45
And why does the newest version not work for you?

**Comment by goldencubegames** [comment] 2022-08-10 06:36
It does not work because jobrunr can not find any Background Job Servers. It works on local system on windows platform but not on the production where I have linux.

**Comment by rdehuyss** [comment] 2022-08-10 06:46
That must be an issue on your side as there are already over 1000 installations running JobRunr 5.2 or higher. On top of that, no logic has changed in this part (announcing BackgroundJobServers / ... ) and JobRunr is covered by over 2000 unit and integration tests.

Probably you're connecting to the wrong database or so.

**Comment by goldencubegames** [comment] 2022-08-11 19:48
hmm I've deleted all mongo collections thats releates to jobrunr so after production deployment jobrunr creates new one and still could not detect running server... I will try once again

**Comment by goldencubegames** [comment] 2022-08-11 19:59
ok so I tried version [5.1.6](https://mvnrepository.com/artifact/org.jobrunr/jobrunr/5.1.6) but [5.2.0-RC1](https://mvnrepository.com/artifact/org.jobrunr/jobrunr/5.2.0-RC1) does not work

**Comment by goldencubegames** [comment] 2022-08-11 20:09
one more try: I upgraded from 
[5.0.1](https://mvnrepository.com/artifact/org.jobrunr/jobrunr/5.0.1)
to
[5.1.0](https://mvnrepository.com/artifact/org.jobrunr/jobrunr/5.1.0)

and job can be scheduled

I will be checking if all jobs are being scheduled properly

**Comment by rdehuyss** [comment] 2022-08-12 05:24
The bug you are facing is only resolved in JobRunr 5.2.0-RC1. i'll verify if I can reproduce the issue your having later.

**Comment by rdehuyss** [comment] 2022-10-11 09:07
Then you're having issues with DB (connecting to wrong DB or so?).

It's used in over 1000 production environments, also on linux.
