### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by cap10** [jobrunr/jobrunr#798] opened 2023-06-30 09:12 UTC
### Runtime information
- __Timestamp__: 2023-06-23T15:36:18.482567296Z
- __Location__: BackgroundJobServer 3099329c-e11a-407f-9843-ab1eab0a32b7
- __JobRunr Version__: 6.2.0
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 20
- __Is running from nested jar__: true
- __Is showing CpuAllocationNotification__: false

### Background Job Servers
- BackgroundJobServer id: 3099329c-e11a-407f-9843-ab1eab0a32b7
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2023-06-23T12:48:15.386329Z, lastHeartbeat: 2023-06-23T15:36:08.686926Z)

#### Concurrent modified jobs:
Job id: a807ec4b-2d06-43fe-b160-025372814068
	Local version: 2222; Storage version: 2223
	Local state: DELETED (at 2023-06-23T15:34:48.286776281Z) ← PROCESSING (updated at 2023-06-23T15:34:48.277611566Z on BackgroundJobServer 3099329c-e11a-407f-9843-ab1eab0a32b7 and started at 2023-06-23T13:16:50.783935792Z) ← ENQUEUED (at 2023-06-23T12:49:31.622171881Z) ← SCHEDULED (at 2023-06-23T12:49:16.586479832Z) ← FAILED (at 2023-06-23T12:49:16.584900419Z) ← PROCESSING (updated at 2023-06-23T12:46:41.259911227Z on BackgroundJobServer e7931dd5-9d05-402f-8498-2a49cd435985 and started at 2023-06-23T09:03:41.303131744Z)
	Storage state: DELETED (at 2023-06-23T15:34:48.227519238Z) ← PROCESSING (updated at 2023-06-23T15:34:33.252528336Z on BackgroundJobServer 3099329c-e11a-407f-9843-ab1eab0a32b7 and started at 2023-06-23T13:16:50.783935792Z) ← ENQUEUED (at 2023-06-23T12:49:31.622171881Z) ← SCHEDULED (at 2023-06-23T12:49:16.586479832Z) ← FAILED (at 2023-06-23T12:49:16.584900419Z) ← PROCESSING (updated at 2023-06-23T12:46:41.259911227Z on BackgroundJobServer e7931dd5-9d05-402f-8498-2a49cd435985 and started at 2023-06-23T09:03:41.303131744Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:76)
	at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:46)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:75)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)

```

**Comment by rdehuyss** [comment] 2023-06-30 17:02
Duplicate of #516

**Closed by rdehuyss** 2023-06-30 17:02 UTC
