### ISSUE TITLE
Could not resolve ConcurrentJobModificationException

### ISSUE THREAD

**Issue by jamesfredleyallied** [jobrunr/jobrunr#658] opened 2023-01-11 17:28 UTC
### Runtime information
- __Timestamp__: 2022-12-16T22:20:26.732612Z
- __Location__: BackgroundJobServer 2b6cf0da-de86-47e4-8556-563bdcd4c56a
- __JobRunr Version__: 5.3.4
- __StorageProvider__: org.jobrunr.storage.sql.mariadb.MariaDbStorageProvider
- __Java Version__: 11.0.13
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: 6f9696c5-5976-406e-8e03-99105f431513
(workerPoolSize: 2, pollIntervalInSeconds: 15, firstHeartbeat: 2022-12-15T22:05:08.459927Z, lastHeartbeat: 2022-12-16T22:20:21.285211Z)
- BackgroundJobServer id: ecaba857-88b2-40a3-b057-d89e45c0efb6
(workerPoolSize: 2, pollIntervalInSeconds: 15, firstHeartbeat: 2022-12-15T22:05:10.486175Z, lastHeartbeat: 2022-12-16T22:20:26.091060Z)
- BackgroundJobServer id: 12f11818-1a38-4572-9f88-8347a9c02ded
(workerPoolSize: 2, pollIntervalInSeconds: 15, firstHeartbeat: 2022-12-16T20:48:22.647589Z, lastHeartbeat: 2022-12-16T22:20:12.390941Z)
- BackgroundJobServer id: 2b6cf0da-de86-47e4-8556-563bdcd4c56a
(workerPoolSize: 2, pollIntervalInSeconds: 15, firstHeartbeat: 2022-12-16T20:48:23.159356Z, lastHeartbeat: 2022-12-16T22:20:12.774069Z)

#### Concurrent modified jobs:
Job id: e19d4d81-1cab-4c5c-b8ec-98d5e5635129
Occurred at: 2022-12-16T22:20:26.732574Z
	Local version: 53; Storage version: 54
	Local state: DELETED (at 2022-12-16T22:18:56.537332Z) ← PROCESSING (updated at 2022-12-16T22:18:56.515713Z on BackgroundJobServer 2b6cf0da-de86-47e4-8556-563bdcd4c56a and started at 2022-12-16T22:18:49.649436Z) ← ENQUEUED (at 2022-12-16T22:18:26.702892Z) ← FAILED (at 2022-12-16T22:10:48.302916Z) ← PROCESSING (updated at 2022-12-16T22:10:41.104982Z on BackgroundJobServer 12f11818-1a38-4572-9f88-8347a9c02ded and started at 2022-12-16T22:07:25.941799Z) ← ENQUEUED (at 2022-12-16T22:07:18.093503Z) ← SCHEDULED (at 2022-12-16T22:07:05.740489Z) ← FAILED (at 2022-12-16T22:07:05.739900Z)
	Storage state: DELETED (at 2022-12-16T22:18:50.957707Z) ← PROCESSING (updated at 2022-12-16T22:18:49.649436Z on BackgroundJobServer 2b6cf0da-de86-47e4-8556-563bdcd4c56a and started at 2022-12-16T22:18:49.649436Z) ← ENQUEUED (at 2022-12-16T22:18:26.702892Z) ← FAILED (at 2022-12-16T22:10:48.302916Z) ← PROCESSING (updated at 2022-12-16T22:10:41.104982Z on BackgroundJobServer 12f11818-1a38-4572-9f88-8347a9c02ded and started at 2022-12-16T22:07:25.941799Z) ← ENQUEUED (at 2022-12-16T22:07:18.093503Z) ← SCHEDULED (at 2022-12-16T22:07:05.740489Z) ← FAILED (at 2022-12-16T22:07:05.739900Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:219)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:91)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by rdehuyss** [comment] 2023-01-11 22:09
Duplicate of #516 .

**Closed by rdehuyss** 2023-01-11 22:09 UTC
