### ISSUE TITLE
[BUG] Getting exception while incrementing successful jobs in jobrunr_metadata due to which background job server is shutting down

### ISSUE THREAD

**Issue by shivamkapoor9999** [jobrunr/jobrunr#677] opened 2023-02-06 10:09 UTC
### JobRunr Version

5.3.2

### JDK Version

8

### Your SQL / NoSQL database

MySQL 8.0.23

### What happened?

Getting below exception multiple times:
```java
FATAL - JobRunr encountered too many processing exceptions. Shutting down.
org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:83)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.jobrunr.storage.StorageException: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Truncated incorrect CHAR(10) value: '1.000000000000000000000000000000'
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.publishTotalAmountOfSucceededJobs(DefaultSqlStorageProvider.java:366)
	at org.jobrunr.storage.ThreadSafeStorageProvider.publishTotalAmountOfSucceededJobs(ThreadSafeStorageProvider.java:199)
	at org.jobrunr.server.JobZooKeeper.checkForSucceededJobsThanCanGoToDeletedState(JobZooKeeper.java:142)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:99)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	... 6 common frames omitted
Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Truncated incorrect CHAR(10) value: '1.000000000000000000000000000000'
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
	at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:633)
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:417)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.jobrunr.storage.sql.common.db.Sql.insertOrUpdate(Sql.java:149)
	at org.jobrunr.storage.sql.common.db.Sql.update(Sql.java:130)
	at org.jobrunr.storage.sql.common.MetadataTable.incrementCounter(MetadataTable.java:66)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.publishTotalAmountOfSucceededJobs(DefaultSqlStorageProvider.java:363)
	... 10 common frames omitted
```

It's similar to this issue - https://github.com/jobrunr/jobrunr/issues/317, it says fixed in v5 but I'm using version 5.3.2 and still getting it

### How to reproduce?

```java
   BackgroundJob.enqueue(() -> service.helpMe());
```

**Comment by rdehuyss** [comment] 2023-02-06 12:44
Hi @shivamkapoor9999 ,

I also tried to reproduce this issue but I am unable to do so. Can you setup a Github repo that reproduces this? I've also reached out to you via LinkedIn.

**Comment by shivamkapoor9999** [comment] 2023-02-06 13:16
Hi @rdehuyss,
Have you tried with setting jdbcCompliantTruncation=true (which is default value) for mysql?

**Comment by rdehuyss** [comment] 2023-02-06 14:08
Yes, I tried with the following connections string:

spring.datasource.url=jdbc:mysql://localhost:3306/mysql?jdbcCompliantTruncation=true

**Comment by rdehuyss** [comment] 2023-02-07 13:42
I've tried the above and I am still unable to reproduce it... with me, the counter successfully updates.

**Comment by rdehuyss** [comment] 2023-02-10 08:47
Closing as no reproducible scenario is present. Feel free to create one (a GitHub repo) and comment on this issue. I'll reopen this issue then.

**Closed by rdehuyss** 2023-02-10 08:47 UTC
Labels: Awaiting feedback
