### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by tifacom** [jobrunr/jobrunr#655] opened 2023-01-04 08:39 UTC
### Runtime information
- __Timestamp__: 2022-12-31T05:16:05.504613461Z
- __Location__: BackgroundJobServer 0878e3d7-870a-419b-9907-48ace44b19e6
- __JobRunr Version__: 5.3.0
- __StorageProvider__: org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider
- __Java Version__: 17.0.2
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: 753e5449-7366-4d10-afd1-bf9990eb6f13
(workerPoolSize: 2, pollIntervalInSeconds: 15, firstHeartbeat: 2022-12-28T07:01:54.941Z, lastHeartbeat: 2022-12-31T05:15:53.695Z)

#### Concurrent modified jobs:
Job id: 9d960d6b-ec06-45e4-abb0-b891669eb3c3
	Local version: 16; Storage version: 17
	Local state: PROCESSING (updated at 2022-12-31T05:16:05.222687209Z on BackgroundJobServer 0878e3d7-870a-419b-9907-48ace44b19e6 and started at 2022-12-31T05:13:45.285279698Z) ← ENQUEUED (at 2022-12-31T05:13:38.987602295Z) ← SCHEDULED (at 2022-12-31T05:10:08.740986209Z) ← FAILED (at 2022-12-31T05:10:08.740858303Z) ← PROCESSING (updated at 2022-12-31T05:08:55.781565968Z on BackgroundJobServer 0878e3d7-870a-419b-9907-48ace44b19e6 and started at 2022-12-31T05:07:53.859445961Z) ← ENQUEUED (at 2022-12-31T05:07:53.583656088Z)
	Storage state: SCHEDULED (at 2022-12-31T05:15:39.127407776Z) ← FAILED (at 2022-12-31T05:15:39.127194393Z) ← PROCESSING (updated at 2022-12-31T05:14:32.695860265Z on BackgroundJobServer 0878e3d7-870a-419b-9907-48ace44b19e6 and started at 2022-12-31T05:13:45.285279698Z) ← ENQUEUED (at 2022-12-31T05:13:38.987602295Z) ← SCHEDULED (at 2022-12-31T05:10:08.740986209Z) ← FAILED (at 2022-12-31T05:10:08.740858303Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:223)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:91)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by rdehuyss** [comment] 2023-01-04 10:37
Are you running on shared hosting (e.g. Amazon / Azure / ... ) ? Or are you doing stuff that causes a lot of garbage collection? 

JobRunr has a background thread that updates the job every 15 seconds (so that it knows that it is still in progress) but from your issue I notice that is unable to run for over a minute. This happens when your JVM does not get any CPU cycles at all for over a minute.

**Comment by tifacom** [comment] 2023-01-04 14:14
I'm running on a Kubernetes cluster with 2 instances of my application (2 pods),

**Comment by rdehuyss** [comment] 2023-01-04 14:30
@tifacom : how come the pod was stuck?

**Comment by tifacom** [comment] 2023-01-04 16:27
Still under investigation

**Comment by rdehuyss** [comment] 2023-01-09 10:25
Closing this as the pod stuckness is probably unrelated to JobRunr. Feel free to reopen if you found that the root cause is caused by JobRunr.

I think the `ConcurrentJobModificationException` is still relevant as it is not expected and a side-effect of the pod that was stuck.

**Closed by rdehuyss** 2023-01-09 10:25 UTC
