### ISSUE TITLE
[BUG] No BackgroundJobServer after exception at Job execution

### ISSUE THREAD

**Issue by ManosKaravas** [jobrunr/jobrunr#1136] opened 2024-10-14 13:33 UTC
### JobRunr Version

7.2.0

### JDK Version

Java 17.0.5

### Your SQL / NoSQL database

PostgreSQL 14.5

### What happened?

A bug happened! After a job is being processed and an exception (not handled properly) occurs, current master BackgourndJobServer is removed and no other takes its place, setting new entries jobs as enqueued infinitely.
Solution to problem so far : Debug/fix bad request that causes the exception or potential data issue and Restart the application.

### How to reproduce?

```java
   UUID id = UUID.fromString(valueAsUuid);
```
Above is a snippet code where valueAsUuid is null. This is just an example that caused Jobrunr to stay without BackgroundJobServer.

**Comment by rdehuyss** [comment] 2024-10-14 14:07
Hi @ManosKaravas - we have 5000 tests and test also that the master is recovered so this issue would surprise a lot...

Can you create a reproducer as I don't know where to add the code related to the UUID?

**Comment by ManosKaravas** [comment] 2024-10-15 08:46
Hello @rdehuyss ! Thanks for your fast reply! This is not related only with the UUID exception. I have encountered occasions many times where API restart was the only solution. Each time an exception not handled properly from my side caused master not be recovered. The last error led Jobrunr stay without master server for 4 days before noticing.
Basic configuration at my yaml file in order for you to have a fully scope ->
 jobrunr:
    background-job-server:
      enabled: true
      worker-count: 10
      poll-interval-in-seconds: 5
      metrics:
        enabled: true
    dashboard:
      enabled: false
    database:
      type: "sql"
      skip-create: true
      table-prefix: "public."
    jobs:
      default-number-of-retries: 0
      retry-back-off-time-seed: 3
    job-scheduler:
      enabled: true
      
Also, previous time an error occured produced the below warning message. I have encountered same warning before long time and as I didn't see it again, I thought it would have been solved in some release. Maybe it will be helpful for you to trace the error.
09-10-2024 12:05:44.317 [backgroundjob-zookeeper-pool-3-thread-2] WARN  o.j.s.JobSteward->run() - JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
...
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: 4ea3f350-5653-4f6b-880d-d7c32bde0fd0, 6f0421cc-a8e4-416f-ab87-66dd6102cde2

Finally, I will try reproduce an error with master server as I think it's quite deterministic based on my experience working with Jobrunr and let you know.

**Comment by rdehuyss** [comment] 2024-10-15 09:39
Hi @ManosKaravas - the only reason the server stops is because of these `ConcurrentJobModificationException`. In case this happens, the dashboard shows you this and it provides all the information for us to diagnose this.

But again, I'm curious in your example github repo that reproduces the issue.

**Comment by rdehuyss** [comment] 2024-10-18 08:38
Hi @ManosKaravas - do you have an update on this? We try to limit the amount of issues as small as possible and if we don't receive feedback or a reproducer, we prefer to close the issue.

**Comment by rdehuyss** [comment] 2024-10-21 06:22
Hi @ManosKaravas - we will close this issue by the end of the week if you cannot reproduce this.

Regarding your other feedback:
> The last error led Jobrunr stay without master server for 4 days before noticing.

This means you did not enable Spring Boot / Quarkus / healthchecks. JobRunr automatically participates in these healthchecks so you should monitor those.

**Comment by ManosKaravas** [comment] 2024-10-21 08:14
Hello @rdehuyss ! I will try to reproduce this and capture it via recording within this week! 
I'm sorry I didn't manage to send a feedback so far as I was quite busy.
Thank you for your comment about healthchecks! I will check it out.

**Comment by rdehuyss** [comment] 2024-10-22 07:22
Hi @ManosKaravas , great - please do not provide a recording but a Github repo that reproduces it!

Thx!

**Comment by rdehuyss** [comment] 2024-10-28 09:35
Closing due to no reproducer.

**Closed by rdehuyss** 2024-10-28 09:35 UTC
Labels: Awaiting feedback
