### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by dizzzyroma** [jobrunr/jobrunr#587] opened 2022-10-21 17:26 UTC
### Runtime information
- __Timestamp__: 2022-10-19T18:47:45.218029532Z
- __Location__: BackgroundJobServer 2c3970a2-23bb-4920-88e7-e730c38dd7c8
- __JobRunr Version__: 5.1.4
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17.0.2
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: 2c3970a2-23bb-4920-88e7-e730c38dd7c8
(workerPoolSize: 4, pollIntervalInSeconds: 15, firstHeartbeat: 2022-10-19T18:42:13.842072Z, lastHeartbeat: 2022-10-19T18:47:43.961868Z)

#### Concurrent modified jobs:
Job id: 2e3965c9-bcce-3460-847f-663fd4eb6284
	Local version: 15; Storage version: 16
	Local state: DELETED (at 2022-10-19T18:46:45.174823725Z) ← PROCESSING (updated at 2022-10-19T18:46:45.172055441Z on BackgroundJobServer 2c3970a2-23bb-4920-88e7-e730c38dd7c8 and started at 2022-10-19T18:43:27.572525956Z) ← ENQUEUED (at 2022-10-19T10:49:53.161340799Z)
	Storage state: DELETED (at 2022-10-19T18:46:41.532417212Z) ← PROCESSING (updated at 2022-10-19T18:46:30.159330397Z on BackgroundJobServer 2c3970a2-23bb-4920-88e7-e730c38dd7c8 and started at 2022-10-19T18:43:27.572525956Z) ← ENQUEUED (at 2022-10-19T10:49:53.161340799Z)
Job id: 39bbad73-0caf-39dd-8f9a-263098780bc3
	Local version: 15; Storage version: 16
	Local state: DELETED (at 2022-10-19T18:46:15.153872001Z) ← PROCESSING (updated at 2022-10-19T18:46:15.148473623Z on BackgroundJobServer 2c3970a2-23bb-4920-88e7-e730c38dd7c8 and started at 2022-10-19T18:42:46.649964098Z) ← ENQUEUED (at 2022-10-18T16:46:53.927067086Z)
	Storage state: DELETED (at 2022-10-19T18:46:14.712865683Z) ← PROCESSING (updated at 2022-10-19T18:46:00.138253675Z on BackgroundJobServer 2c3970a2-23bb-4920-88e7-e730c38dd7c8 and started at 2022-10-19T18:42:46.649964098Z) ← ENQUEUED (at 2022-10-18T16:46:53.927067086Z)
Job id: 3f40bbd8-4f8f-3493-b2c6-740b4d43983d
	Local version: 19; Storage version: 20
	Local state: DELETED (at 2022-10-19T18:46:45.176392050Z) ← PROCESSING (updated at 2022-10-19T18:46:45.172109048Z on BackgroundJobServer 2c3970a2-23bb-4920-88e7-e730c38dd7c8 and started at 2022-10-19T18:42:24.392144852Z) ← ENQUEUED (at 2022-10-18T16:43:53.936161674Z)
	Storage state: DELETED (at 2022-10-19T18:46:31.434854957Z) ← PROCESSING (updated at 2022-10-19T18:46:30.159399096Z on BackgroundJobServer 2c3970a2-23bb-4920-88e7-e730c38dd7c8 and started at 2022-10-19T18:42:24.392144852Z) ← ENQUEUED (at 2022-10-18T16:43:53.936161674Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:212)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:92)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### Runtime information
- __Timestamp__: 2022-10-19T18:53:14.037162330Z
- __Location__: BackgroundJobServer a9d91263-23eb-467b-bf04-d81d459a6f61
- __JobRunr Version__: 5.1.4
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17.0.2
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: a9d91263-23eb-467b-bf04-d81d459a6f61
(workerPoolSize: 4, pollIntervalInSeconds: 15, firstHeartbeat: 2022-10-19T18:50:12.739539Z, lastHeartbeat: 2022-10-19T18:53:12.821487Z)

#### Concurrent modified jobs:
Job id: 1221fe61-2556-3e87-bb83-e144d4dbb8a9
	Local version: 6697; Storage version: 6698
	Local state: DELETED (at 2022-10-19T18:51:43.978471113Z) ← PROCESSING (updated at 2022-10-19T18:51:43.971353416Z on BackgroundJobServer a9d91263-23eb-467b-bf04-d81d459a6f61 and started at 2022-10-19T18:50:13.825574228Z) ← ENQUEUED (at 2022-10-19T18:43:30.004453813Z) ← SCHEDULED (at 2022-10-19T18:43:14.984215561Z) ← FAILED (at 2022-10-19T18:43:14.983627022Z) ← PROCESSING (updated at 2022-10-19T18:41:45.931398240Z on BackgroundJobServer 929c64e6-22f4-4637-832d-635ba832012d and started at 2022-10-18T14:49:06.637036985Z)
	Storage state: DELETED (at 2022-10-19T18:51:33.726145937Z) ← PROCESSING (updated at 2022-10-19T18:51:28.960285453Z on BackgroundJobServer a9d91263-23eb-467b-bf04-d81d459a6f61 and started at 2022-10-19T18:50:13.825574228Z) ← ENQUEUED (at 2022-10-19T18:43:30.004453813Z) ← SCHEDULED (at 2022-10-19T18:43:14.984215561Z) ← FAILED (at 2022-10-19T18:43:14.983627022Z) ← PROCESSING (updated at 2022-10-19T18:41:45.931398240Z on BackgroundJobServer 929c64e6-22f4-4637-832d-635ba832012d and started at 2022-10-18T14:49:06.637036985Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:212)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:92)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### Runtime information
- __Timestamp__: 2022-10-19T21:44:06.348211920Z
- __Location__: BackgroundJobServer 874f907b-b8bb-4d0a-8e8e-ee7bec816f65
- __JobRunr Version__: 5.1.4
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17.0.2
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: 874f907b-b8bb-4d0a-8e8e-ee7bec816f65
(workerPoolSize: 4, pollIntervalInSeconds: 15, firstHeartbeat: 2022-10-19T21:43:35.311015Z, lastHeartbeat: 2022-10-19T21:44:05.318984Z)
- BackgroundJobServer id: d32b7d95-0b80-4484-9c97-a94e6f9705dc
(workerPoolSize: 10, pollIntervalInSeconds: 15, firstHeartbeat: 2022-10-20T00:42:05.282195Z, lastHeartbeat: 2022-10-20T00:43:53.960454Z)

#### Concurrent modified jobs:
Job id: bf222c13-76d7-339e-9420-545d5aa331a9
	Local version: 193; Storage version: 194
	Local state: PROCESSING (updated at 2022-10-19T21:44:06.343606996Z on BackgroundJobServer 874f907b-b8bb-4d0a-8e8e-ee7bec816f65 and started at 2022-10-19T20:55:17.788699399Z) ← ENQUEUED (at 2022-10-19T20:55:17.569863653Z)
	Storage state: SCHEDULED (at 2022-10-19T21:43:24.421852Z) ← FAILED (at 2022-10-19T21:43:24.421354Z) ← PROCESSING (updated at 2022-10-19T21:43:04.452974102Z on BackgroundJobServer 874f907b-b8bb-4d0a-8e8e-ee7bec816f65 and started at 2022-10-19T20:55:17.788699399Z) ← ENQUEUED (at 2022-10-19T20:55:17.569863653Z)
Job id: f3975477-e2e0-37f1-b887-c61e7892a7bd
	Local version: 232; Storage version: 233
	Local state: PROCESSING (updated at 2022-10-19T21:44:06.343607545Z on BackgroundJobServer 874f907b-b8bb-4d0a-8e8e-ee7bec816f65 and started at 2022-10-19T20:45:32.414769872Z) ← ENQUEUED (at 2022-10-19T20:45:17.579403752Z)
	Storage state: SCHEDULED (at 2022-10-19T21:43:24.422028Z) ← FAILED (at 2022-10-19T21:43:24.421463Z) ← PROCESSING (updated at 2022-10-19T21:43:04.452974703Z on BackgroundJobServer 874f907b-b8bb-4d0a-8e8e-ee7bec816f65 and started at 2022-10-19T20:45:32.414769872Z) ← ENQUEUED (at 2022-10-19T20:45:17.579403752Z)
Job id: ec5e7853-48cf-3c5c-99cc-aadab0ed618f
	Local version: 432; Storage version: 433
	Local state: PROCESSING (updated at 2022-10-19T21:44:06.343608009Z on BackgroundJobServer 874f907b-b8bb-4d0a-8e8e-ee7bec816f65 and started at 2022-10-19T19:55:30.625884194Z) ← ENQUEUED (at 2022-10-19T19:55:17.583900432Z)
	Storage state: SCHEDULED (at 2022-10-19T21:43:24.422153Z) ← FAILED (at 2022-10-19T21:43:24.421515Z) ← PROCESSING (updated at 2022-10-19T21:43:04.452974968Z on BackgroundJobServer 874f907b-b8bb-4d0a-8e8e-ee7bec816f65 and started at 2022-10-19T19:55:30.625884194Z) ← ENQUEUED (at 2022-10-19T19:55:17.583900432Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:212)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:92)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by rdehuyss** [comment] 2022-10-21 21:53
Duplicate of #516

**Closed by rdehuyss** 2022-10-21 21:53 UTC
