### ISSUE TITLE
[BUG] Severe JobRunr Exception

### ISSUE THREAD

**Issue by brendan-coulson** [jobrunr/jobrunr#550] opened 2022-09-06 09:12 UTC
### Runtime information
 __Timestamp__: 2022-09-01T06:40:59.370Z
__Location__: BackgroundJobServer e058fd40-3fce-42e9-9995-49088887f03e
__JobRunr Version__: 5.1.8
__StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
__Java Version__: 1.8.0_342
__Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: e058fd40-3fce-42e9-9995-49088887f03e(workerPoolSize: 32, pollIntervalInSeconds: 5, firstHeartbeat: 2022-08-31T07:55:25.449Z, lastHeartbeat: 2022-09-01T06:40:57.535Z)
- BackgroundJobServer id: e5d8eddb-7411-45b4-a1a7-4b14ff93238a(workerPoolSize: 32, pollIntervalInSeconds: 5, firstHeartbeat: 2022-08-31T07:55:26.912Z, lastHeartbeat: 2022-09-01T06:40:55.237Z)
- BackgroundJobServer id: 7dc877e0-9ca6-463a-aac4-cf45b9575bc7(workerPoolSize: 32, pollIntervalInSeconds: 5, firstHeartbeat: 2022-08-31T07:55:38.127Z, lastHeartbeat: 2022-09-01T06:40:55.069Z)
 
### Diagnostics from exception#### 
Concurrent modified jobs:Job id: 79ebda5d-036d-4648-bd0e-9ba79b2f1e75
Local version: 8873;
Storage version: 8874	
Local state: DELETED (at 2022-09-01T06:40:28.958Z) ← PROCESSING (updated at 2022-09-01T06:40:28.909Z on BackgroundJobServer e058fd40-3fce-42e9-9995-49088887f03e and started at 2022-08-31T18:04:55.627Z) ← ENQUEUED (at 2022-08-31T18:04:55.581Z) ← SCHEDULED (at 2022-08-31T18:04:55.571Z)	
Storage state: DELETED (at 2022-09-01T06:40:24.542Z) ← PROCESSING (updated at 2022-09-01T06:40:23.760Z on BackgroundJobServer e058fd40-3fce-42e9-9995-49088887f03e and started at 2022-08-31T18:04:55.627Z) ← ENQUEUED (at 2022-08-31T18:04:55.581Z) ← SCHEDULED (at 2022-08-31T18:04:55.571Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:236)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:93)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)```

**Comment by rdehuyss** [comment] 2022-09-06 09:27
Duplicate of #516.

**Closed by rdehuyss** 2022-09-06 09:27 UTC
