### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by Skillkiller** [jobrunr/jobrunr#787] opened 2023-06-12 23:04 UTC
### Runtime information
- __Timestamp__: 2023-06-11T12:45:25.162127600Z
- __Location__: BackgroundJobServer 57f1cedb-27da-46ba-821a-17efc5092627
- __JobRunr Version__: 5.3.3
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17.0.4.1
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 57f1cedb-27da-46ba-821a-17efc5092627
(workerPoolSize: 3, pollIntervalInSeconds: 15, firstHeartbeat: 2023-06-11T12:43:51.171504Z, lastHeartbeat: 2023-06-11T12:45:22.339651Z)

#### Concurrent modified jobs:
Job id: 5ef9b031-51e6-4d50-a52a-252cae2112ba
	Local version: 11; Storage version: 12
	Local state: DELETED (at 2023-06-11T12:44:40.003975300Z) ← PROCESSING (updated at 2023-06-11T12:44:39.993518Z on BackgroundJobServer 57f1cedb-27da-46ba-821a-17efc5092627 and started at 2023-06-11T12:43:53.005000500Z) ← ENQUEUED (at 2023-06-11T12:43:52.547506Z) ← SCHEDULED (at 2023-06-11T12:42:33.940651800Z) ← FAILED (at 2023-06-11T12:42:33.936219100Z) ← PROCESSING (updated at 2023-06-11T12:41:29.802610300Z on BackgroundJobServer f14c85ab-7a50-4369-9d26-5f009dc38a9d and started at 2023-06-11T12:40:43.509415800Z)
	Storage state: DELETED (at 2023-06-11T12:44:28.304399500Z) ← PROCESSING (updated at 2023-06-11T12:44:23.959960Z on BackgroundJobServer 57f1cedb-27da-46ba-821a-17efc5092627 and started at 2023-06-11T12:43:53.005000500Z) ← ENQUEUED (at 2023-06-11T12:43:52.547506Z) ← SCHEDULED (at 2023-06-11T12:42:33.940651800Z) ← FAILED (at 2023-06-11T12:42:33.936219100Z) ← PROCESSING (updated at 2023-06-11T12:41:29.802610300Z on BackgroundJobServer f14c85ab-7a50-4369-9d26-5f009dc38a9d and started at 2023-06-11T12:40:43.509415800Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:223)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:91)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by Skillkiller** [comment] 2023-06-12 23:06
I think the error was provoked when I terminated the Spring application in which JobRunr is also running right after starting it, before the startup process was completed. I don't know exactly because I saw the notice in the dashboard later.

**Comment by rdehuyss** [comment] 2023-06-13 04:38
I don't provide support on older versions of JobRunr. Please upgrade to the latest version.

Also looks like a duplicate of #516.

**Closed by rdehuyss** 2023-06-13 04:38 UTC
