### ISSUE TITLE
JobRunr BackgroundJobServer failed to start In DB2_10.5[BUG]

### ISSUE THREAD

**Issue by VincentRoy-Git** [jobrunr/jobrunr#590] opened 2022-10-25 01:11 UTC
**Are you running the latest version of JobRunr?**
Yes 
If no, please first upgrade to the latest JobRunr version and check whether the issue still exists.

**Describe the bug**
```java
org.jobrunr.storage.StorageException: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=LIMIT;;FETCH FIRST <n> ROWS ONLY, DRIVER=4.25.13
        at org.jobrunr.storage.sql.common.db.SqlSpliterator.init(SqlSpliterator.java:62) ~[jobrunr-5.3.0.jar:5.3.0]
        at org.jobrunr.storage.sql.common.db.SqlSpliterator.tryAdvance(SqlSpliterator.java:35) ~[jobrunr-5.3.0.jar:5.3.0]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:1.8.0_201]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[na:1.8.0_201]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[na:1.8.0_201]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_201]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[na:1.8.0_201]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_201]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[na:1.8.0_201]
        at org.jobrunr.storage.sql.common.BackgroundJobServerTable.getLongestRunningBackgroundJobServerId(BackgroundJobServerTable.java:97) ~[jobrunr-5.3.0.jar:5.3.0]
        at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.getLongestRunningBackgroundJobServerId(DefaultSqlStorageProvider.java:116) ~[jobrunr-5.3.0.jar:5.3.0]
        at org.jobrunr.storage.ThreadSafeStorageProvider.getLongestRunningBackgroundJobServerId(ThreadSafeStorageProvider.java:74) ~[jobrunr-5.3.0.jar:5.3.0]
        at org.jobrunr.server.ServerZooKeeper.determineIfCurrentBackgroundJobServerIsMaster(ServerZooKeeper.java:115) ~[jobrunr-5.3.0.jar:5.3.0]
        at org.jobrunr.server.ServerZooKeeper.announceBackgroundJobServer(ServerZooKeeper.java:71) ~[jobrunr-5.3.0.jar:5.3.0]
        at org.jobrunr.server.ServerZooKeeper.run(ServerZooKeeper.java:47) ~[jobrunr-5.3.0.jar:5.3.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_201]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=LIMIT;;FETCH FIRST <n> ROWS ONLY, DRIVER=4.25.13
```

**Environment**
I'm using JobRunr version: (5.3.0)
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): (Java 1.8.0_262)
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): (DB2/NT64 10.5)

**How to Reproduce**
Provide a simple Github project or code fragment which shows how to reproduce the issue (ideally a Github repo).
```java
@SpringBootApplication
public class HmsApplication implements WebMvcConfigurer {

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("doc.html").addResourceLocations("classpath:/META-INF/resources/");
        registry.addResourceHandler("/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/");
    }

    public static void main(String[] args) {
        SpringApplication.run(HmsApplication.class, args);
    }

    @Bean
    public JobRunrConfigurationResult initJobRunr(ApplicationContext applicationContext) {
        return JobRunr.configure()
                .useJobActivator(applicationContext::getBean)
                .useStorageProvider(SqlStorageProviderFactory
                        .using(applicationContext.getBean(DataSource.class)))
                .useBackgroundJobServer()
                .useDashboard(8001)
                .initialize();
    }

    @Bean
    public JobScheduler initJobScheduler(JobRunrConfigurationResult jobRunrConfigurationResult) {
        return jobRunrConfigurationResult.getJobScheduler();
    }

    @Bean
    public JobRequestScheduler initJobRequestScheduler(JobRunrConfigurationResult jobRunrConfigurationResult) {
        return jobRunrConfigurationResult.getJobRequestScheduler();
    }

}
```

**Expected behavior**

**Additional context**

**Comment by rdehuyss** [comment] 2022-10-25 06:55
Thanks for recreating the issue. I just checked and I'm unable to reproduce this on DB2 11.5. 

I only have DB2 11.5 to my disposal (via docker hub, there are no images for DB2 10.5) but from what I've read, the limit clause was added in DB2 7.1/7.2 so it should also be supported in DB2 10.5.

I currently don't know how to proceed, to be honest.

**Comment by rdehuyss** [comment] 2022-10-25 06:56
Are you using the correct DB2 driver? I've read that in some cases, the driver may be causing this issue.

**Comment by rdehuyss** [comment] 2022-10-25 06:58
See also the [DB2 StorageProviderTests](https://github.com/jobrunr/jobrunr/blob/master/core/src/test/java/org/jobrunr/storage/sql/db2/).

**Comment by VincentRoy-Git** [comment] 2022-10-25 07:14
https://www.ibm.com/docs/en/db2/10.5?topic=features-db2-compatibility-vector-registry-variable
I think this maybe the reason. Thank you for your answers

**Comment by VincentRoy-Git** [comment] 2022-10-25 07:16
I'm trying to use FETCH command to replace LIMIT

**Comment by VincentRoy-Git** [comment] 2022-10-28 06:07
![image](https://user-images.githubusercontent.com/59716599/198513906-3cb0e439-939e-482f-8645-f14e3a9efdb9.png)
I created these classes to override the limit methods.
such as: 
public class DB2BackgroundJobServerTable extends BackgroundJobServerTable {
    public DB2BackgroundJobServerTable(Connection connection, Dialect dialect, String tablePrefix) {
        super(connection, dialect, tablePrefix);
    }

    @Override
    public UUID getLongestRunningBackgroundJobServerId() {
        return (UUID)this.select("id from jobrunr_backgroundjobservers order by firstHeartbeat ASC fetch first 1 rows only").map((sqlResultSet) -> {
            return sqlResultSet.asUUID("id");
        }).findFirst().orElseThrow(() -> {
            return JobRunrException.shouldNotHappenException("No servers available?!");
        });
    }
}

**Comment by rdehuyss** [comment] 2022-10-28 07:21
The only thing you would need to do though is create a `Dialect` for DB2 and all should be solved. Feel free to contact me if you need any help with that.

As I understand your issue is currently solved, I'll close the issue.

**Closed by rdehuyss** 2022-10-28 07:21 UTC
