### ISSUE TITLE
[Feature] Please provide a way to propely restart a BackgroundJobServer

### ISSUE THREAD

**Issue by essentialprogramming** [jobrunr/jobrunr#473] opened 2022-05-28 10:43 UTC
**Is your feature request related to a problem? Please describe.**
If a BackgroundJobServer is not propely closed( for example in case of a StorageProvider failure the ServerZooKeeper will not be propely closed ) , then you cannot start it again to be operational again, because the ServerZooKeeper and the JobZooKeeper are in an inconsitent state. 

**Describe the solution you'd like**
 Please provide a public method in BackgroundJobServer `forceStop` which will just not check the condition `if (!this.isStopped())`. This way you can properly close a BackgroundJobServer which was forced closed before due to a StorageProvider failure and start it again. 

**Describe alternatives you've considered**
Now a workaround I can use is to start the BackgroundJobServer ( which will not process anything at this point because the JobZooKeeper is in a dangling state ) , stop the BackgroundJobServer and start the BackgroundJobServer again. Everything works fine after that. 

**Additional context**
Not applicable.

**Comment by essentialprogramming** [comment] 2022-05-28 11:07
public void restart() {
        forceStop();
        start();
    }

    public void stop() {
        if (isStopped()) return;
        forceStop();
    }

    private void forceStop() {
        try (BackgroundJobServerLifecycleLock ignored = lifecycleLock.lock()) {
            LOGGER.info("BackgroundJobServer and BackgroundJobPerformers - stopping (waiting for all jobs to complete - max 10 seconds)");
            isMaster = null;
            stopWorkers();
            stopZooKeepers();
            isRunning = false;
            firstHeartbeat = null;
            LOGGER.info("BackgroundJobServer and BackgroundJobPerformers stopped");
        }
    }

**Comment by essentialprogramming** [comment] 2022-05-28 11:34
PR: https://github.com/jobrunr/jobrunr/pull/474

**Comment by patkujawa-wf** [comment] 2022-05-31 22:28
FYI @rdehuyss 
Even with jobrunr pro, we ran into a situation where this would have been helpful. We were upgrading our AWS Aurora mysql instances and the cloudformation changes took a while. During that time, the primary and replica likely swapped instances and the one jobrunr was connected to became read-only, leading to "An unrecoverable error occurred. Shutting server down...". We ultimately got back up and running by redeploying the service.

Stacktrace:
```
org.jobrunr.storage.StorageException: java.sql.SQLException: The MySQL server is running with the --read-only option so it cannot execute this statement
 at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.signalBackgroundJobServerAlive(DefaultSqlStorageProvider.java)
 at org.jobrunr.storage.ThreadSafeStorageProvider.signalBackgroundJobServerAlive(ThreadSafeStorageProvider.java)
 at org.jobrunr.server.ServerZooKeeper.signalBackgroundJobServerAlive(ServerZooKeeper.java)
 at org.jobrunr.server.ServerZooKeeper.signalBackgroundJobServerAliveAndDoZooKeeping(ServerZooKeeper.java)
 at org.jobrunr.server.ServerZooKeeper.run(ServerZooKeeper.java)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java)
 at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
 at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
 at java.base/java.lang.Thread.run(Thread.java)
Caused by: java.sql.SQLException: The MySQL server is running with the --read-only option so it cannot execute this statement
 at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java)
 at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java)
 at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java)
 at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java)
 at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java)
 at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java)
 at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java)
 at org.jobrunr.storage.sql.common.db.Sql.insertOrUpdate(Sql.java)
 at org.jobrunr.storage.sql.common.db.Sql.update(Sql.java)
 at org.jobrunr.storage.sql.common.BackgroundJobServerTable.signalServerAlive(BackgroundJobServerTable.java)
 at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.signalBackgroundJobServerAlive(DefaultSqlStorageProvider.java)
 ... 10 common frames omitted
```

**Comment by rdehuyss** [comment] 2022-06-02 22:56
Hi @essentialprogramming ,

Thanks for bringing to my attention but I'm not completely following and I prefer to find the root cause: the zookeepers that are in an inconsistent state. Can you reproduce this?

**Comment by essentialprogramming** [comment] 2022-06-07 19:42
Hi @rdehuyss,
 I can simply repoduce the issue by using a cloud database and cut of WIFI for a few secnonds. The database connections will of course not be available during this period. BackgroundJobServer will close, but not in such a way that it can be restarted afterwards. If you call BackgroundJobServer().start() it will NOT start. But of you call BackgroundJobServer().stop() , wait for a few seconds, and then call BackgroundJobServer().start() again, the BackgroundJobServer is up and running again.

**Comment by rdehuyss** [comment] 2022-06-08 05:03
Ok, thanks - this is the info I was looking for. Then in my eyes something is wrong with the closing of the BackgroundJobServer and that should be solved.

**Closed** 2022-06-10 19:49 UTC
Labels: bug
