### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by lemm-leto** [jobrunr/jobrunr#637] opened 2022-12-09 21:10 UTC
### Runtime information
- __Timestamp__: 2022-12-09T16:52:44.860881800Z
- __Location__: BackgroundJobServer 90d8e2b9-9ce3-4d02-ab04-e119944f4e88
- __JobRunr Version__: 5.3.1
- __StorageProvider__: org.jobrunr.storage.sql.mysql.MySqlStorageProvider
- __Java Version__: 16.0.2
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 90d8e2b9-9ce3-4d02-ab04-e119944f4e88
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2022-12-09T16:48:10Z, lastHeartbeat: 2022-12-09T16:52:41Z)

#### Concurrent modified jobs:
Job id: 676aa5cf-9f17-4627-84ae-d387734b7cbb
	Local version: 15; Storage version: 16
	Local state: DELETED (at 2022-12-09T16:52:14.652837500Z) ← PROCESSING (updated at 2022-12-09T16:52:14.643834600Z on BackgroundJobServer 90d8e2b9-9ce3-4d02-ab04-e119944f4e88 and started at 2022-12-09T16:48:42.154651Z) ← ENQUEUED (at 2022-12-09T16:48:30.221765900Z)
	Storage state: DELETED (at 2022-12-09T16:52:11.625464200Z) ← PROCESSING (updated at 2022-12-09T16:51:59.468922100Z on BackgroundJobServer 90d8e2b9-9ce3-4d02-ab04-e119944f4e88 and started at 2022-12-09T16:48:42.154651Z) ← ENQUEUED (at 2022-12-09T16:48:30.221765900Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:223)

	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:91)

	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)

	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)

	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)

	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)

	at java.base/java.lang.Thread.run(Thread.java:831)


```

**Comment by rdehuyss** [comment] 2022-12-10 08:46
Duplicate of #516 .

**Closed by rdehuyss** 2022-12-10 08:46 UTC
