### ISSUE TITLE
[BUG] Calling BackgroundJob.enqueue from kotlin

### ISSUE THREAD

**Issue by FugueDev** [jobrunr/jobrunr#68] opened 2020-11-20 11:58 UTC
**Describe the bug**
Calling BackgroundJob.enque from .kt fails at runtime. 

**Environment**
I'm using version 1.2
I'm running on openJDK 15 
I'm using the following StorageProvider psql 

**To Reproduce**
Provide a simple project or code fragment which shows how to reproduce the issue.
```kotlin
BackgroundJob.enqueue{foo()}
```
Should work since this is a lambda expression

**Error message**
Please provide a lambda expression (e.g. BackgroundJob.enqueue(() -> myService.doWork()) instead of an actual implementation.

**Additional context**
What works for me is to create a java wrapper class that uses java lambda syntax.

**Comment by JoonasC** [comment] 2020-11-20 14:12
@FugueDev Issue #63 is already discussing this problem, could you post your workaround there?

**Comment by rdehuyss** [comment] 2020-11-20 18:45
Duplicate of #63

**Closed by rdehuyss** 2020-11-20 18:45 UTC
