### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by edvinasstaupas** [jobrunr/jobrunr#756] opened 2023-05-04 10:03 UTC
### JobRunr Version

6.0.0

### JDK Version

jdk-18.0.2.1

### Your SQL / NoSQL database

MariaDB 10.6

### What happened?

While processing jobs randomly throws internal exceptions and shuts down.

### How to reproduce?

Waiting in queue 1000+ jobs, 4 workers per server (CPU: 8700k), one server. Around 20 jobs been processed and then exceptions below happen. Does not happen at the same time running it again, but happens most of the time after some time processing. 

### Relevant log output

```shell
2023-05-04T12:56:12.636+03:00  WARN 289800 --- [pool-4-thread-1] org.jobrunr.server.JobZooKeeper          : JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.

org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:77) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:71) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:55) ~[jobrunr-6.0.0.jar:6.0.0]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-05-04T12:56:18.628+03:00  WARN 289800 --- [pool-4-thread-1] org.jobrunr.server.JobZooKeeper          : JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.

org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:77) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:71) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:55) ~[jobrunr-6.0.0.jar:6.0.0]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-05-04T12:56:24.853+03:00  WARN 289800 --- [pool-4-thread-1] org.jobrunr.server.JobZooKeeper          : JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.

org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:77) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:71) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:55) ~[jobrunr-6.0.0.jar:6.0.0]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-05-04T12:56:31.475+03:00  WARN 289800 --- [pool-4-thread-1] org.jobrunr.server.JobZooKeeper          : JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.

org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:77) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:71) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:55) ~[jobrunr-6.0.0.jar:6.0.0]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-05-04T12:56:39.601+03:00  WARN 289800 --- [pool-4-thread-1] org.jobrunr.server.JobZooKeeper          : JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.

org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:77) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:71) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:55) ~[jobrunr-6.0.0.jar:6.0.0]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-05-04T12:56:47.828+03:00 ERROR 289800 --- [pool-4-thread-1] org.jobrunr.server.JobZooKeeper          : FATAL - JobRunr encountered too many processing exceptions. Shutting down.

org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:77) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:71) ~[jobrunr-6.0.0.jar:6.0.0]
        at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:55) ~[jobrunr-6.0.0.jar:6.0.0]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

**Comment by rdehuyss** [comment] 2023-05-04 12:08
On the dashboard page, a warning message is shown about the exceptions you encounter. Please share it here, as without it, I cannot help you I'm afraid.

**Comment by rdehuyss** [comment] 2023-05-04 12:08
See this blog post for more info: https://www.jobrunr.io/en/blog/2021-02-07-v1.3/

**Comment by edvinasstaupas** [comment] 2023-05-04 12:58
I cannot reproduce exceptions at the moment. The only thing I changed was `org.jobrunr.background-job-server.poll-interval-in-seconds` from `15` to `120`. It seems it fixed it. Previously I could not run more than 4 workers. Now I have stable system with 12 workers.
@rdehuyss could you elaborate more on how to work out what is the maximum stable worker count. In your documentation it says 
```
 org.jobrunr.background-job-server.worker-count= #this value normally is defined by the amount of CPU's that are available
 ```
Does this mean my CPU cores, threads or something else?

**Comment by rdehuyss** [comment] 2023-05-04 14:43
Well, the fact that you had it still means something is wrong - increasing the pollIntervalInSeconds just 'hides' the problem. I find it important that the root cause is found.

Regarding your question, please see the [DefaultBackgroundJobServerWorkerPolicy.java](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/server/configuration/DefaultBackgroundJobServerWorkerPolicy.java).

Again, JobRunr automatically collects relevant information to find the cause of this exception in the dashboard. Can you send it over?

**Comment by edvinasstaupas** [comment] 2023-05-04 16:57
As my system is currently stable, I will finish running the jobs. Then try to recreate the exceptions.

**Comment by rdehuyss** [comment] 2023-05-04 18:22
I'll close the issue for now as without it, I cannot do anything l. Feel free to reopen as soon as you have the necessary logs. And, please also upgrade to the latest version as it contains bugfixes.

**Closed by rdehuyss** 2023-05-04 18:22 UTC
