### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by fmalmi** [jobrunr/jobrunr#523] opened 2022-07-21 23:36 UTC
### Runtime information
- __Timestamp__: 2022-07-21T23:26:36.594606Z
- __Location__: BackgroundJobServer 66b744f1-7c70-4619-83f0-312bb065b8b0
- __JobRunr Version__: 5.1.5
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 11.0.14.1
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 66b744f1-7c70-4619-83f0-312bb065b8b0
(workerPoolSize: 8, pollIntervalInSeconds: 15, firstHeartbeat: 2022-07-21T23:21:20.166595Z, lastHeartbeat: 2022-07-21T23:26:35.508502Z)

#### Concurrent modified jobs:
Job id: 890251f9-bee1-4133-b68d-6ef37ec2c1f3
	Local version: 16; Storage version: 17
	Local state: DELETED (at 2022-07-21T23:25:36.513425Z) ← PROCESSING (updated at 2022-07-21T23:25:36.505798Z on BackgroundJobServer 66b744f1-7c70-4619-83f0-312bb065b8b0 and started at 2022-07-21T23:24:36.437038Z) ← ENQUEUED (at 2022-07-21T23:24:36.413859Z) ← SCHEDULED (at 2022-07-21T23:24:31.087128Z) ← FAILED (at 2022-07-21T23:24:31.085677Z) ← PROCESSING (updated at 2022-07-21T23:24:21.390673Z on BackgroundJobServer 66b744f1-7c70-4619-83f0-312bb065b8b0 and started at 2022-07-21T23:22:21.230136Z)
	Storage state: DELETED (at 2022-07-21T23:25:24.570046Z) ← PROCESSING (updated at 2022-07-21T23:25:21.486185Z on BackgroundJobServer 66b744f1-7c70-4619-83f0-312bb065b8b0 and started at 2022-07-21T23:24:36.437038Z) ← ENQUEUED (at 2022-07-21T23:24:36.413859Z) ← SCHEDULED (at 2022-07-21T23:24:31.087128Z) ← FAILED (at 2022-07-21T23:24:31.085677Z) ← PROCESSING (updated at 2022-07-21T23:24:21.390673Z on BackgroundJobServer 66b744f1-7c70-4619-83f0-312bb065b8b0 and started at 2022-07-21T23:22:21.230136Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:212)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:92)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by rdehuyss** [comment] 2022-07-22 07:00
Duplicate of #516

**Closed by rdehuyss** 2022-07-22 07:00 UTC
