### ISSUE TITLE
[Feature] add support for kotlinx.serialization as JsonMapper

### ISSUE THREAD

**Issue by gmariotti** [jobrunr/jobrunr#960] opened 2024-03-15 10:26 UTC
**Is your feature request related to a problem? Please describe.**
With [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization) gaining popularity in the Kotlin space, it would be great to have it as a `JsonMapper` option in JobRunr and avoid the need to have different type of json libraries in the same project.

**Describe the solution you'd like**
A configurable `JsonMapper` that uses `kotlinx.serialization` is added to JobRunr `core` or `language-support`.

**Describe alternatives you've considered**
The only alternative would be to develop it as a separate project, independent of JobRunr.

**Additional context**
If it's okay to have it in JobRunr, I'm open to creating a PR for it.

**Comment by rdehuyss** [comment] 2024-03-15 10:36
Hi @gmariotti , we're definitely open for PR's. The only important thing to keep in mind is to make sure there are some tests.

**Comment by gmariotti** [comment] 2024-03-15 10:39
Thanks for the fast answer @rdehuyss 🙏 in which module should I develop it? In `core`, like the other mappers, or in `language-support`?

**Comment by rdehuyss** [comment] 2024-03-15 10:42
I would do it in the language-support module for kotlin 1.9 as it will only be relevant for Kotlin.. If you add a test that extends the Java `AbstractJsonMapperTest`, I think we're ok (the `AbstractJsonMapperTest` may have to move to TestFixtures though).

**Comment by rdehuyss** [comment] 2024-03-15 10:43
Please also use the v7 branch for your work as we're about to release the first v7 release candidate.

**Comment by alexanderpichler-cpi** [comment] 2024-04-19 11:16
@gmariotti I can help you if you want

**Comment by gmariotti** [comment] 2024-04-20 06:06
@alexanderpichler-cpi I'm hoping to get back to it this weekend, but if I don't, I'll let you know

**Comment by rdehuyss** [comment] 2024-08-14 09:05
Hi @gmariotti , @alexanderpichler-cpi , as I've not received a PR for this, I will close this for now. 

Feel free to open a PR as soon as you have an implementation with `kotlinx.serialization`.

**Closed by rdehuyss** 2024-08-14 09:05 UTC

**Comment by auloin** [comment] 2024-08-14 14:23
Hi @chrisjenx, I don't think your question is directly linked to this issue. Could you open a discussion with the details of what you're trying to achieve?

**Comment by chrisjenx** [comment] 2024-08-14 14:43
I exclusively use kotlinx for serialization.

Is the job builder able to take any custom serializer so I can write my own serializer instead of using gson etc

**Comment by gmariotti** [comment] 2024-08-16 06:32
@rdehuyss unfortunately I never had the chance to get back to this issue and don't think I'll be able to in the short term 😕

@chrisjenx it's possible to write a custom serializer/deserializer for JobRunr using kotlinx.serialization, but you'll have to implement a delegate for every class that JobRunr serializes, which didn't appear to be that trivial when I tried it.

**Comment by chrisjenx** [comment] 2024-08-22 05:23
Unfortunately because the way you wrote your POJO's it makes it very inflexible to use with generator based serialization libraries, also forcing to use JSON is a little annoying.
Basically because GSON/Jackson use reflection they can access and set final fields on classes, most generator based can't as they rely on using primary constructors, and as most of your primary constructors don't expose all the fields for those POJO's it means reflection based serialization are pretty much the only choice right now. 

Anything that is a data class should expose all the fields that would be set via constructors, also how do you do testing? If these are private fields, how would you test these, relying on mocking frameworks to achieve this worries me too.

**Comment by auloin** [comment] 2024-08-22 09:35
@chrisjenx It may not be simple but it's definitely still possible as we currently support JSONB which does not use reflection. We also do have great test coverage for all the features in JobRunr including JSON (de)serialisation, tests are one of the factors that makes JobRunr so popular.

**Comment by chrisjenx** [comment] 2024-08-22 16:03
@auloin I don't follow, yasson also uses reflection to support JSON-B... Is there another library that uses custom serializers that you support I didn't see?

For Example:
`DeletedState` is impossible to deserialize, we only have two fields we care are about, `reason` and `createdAt`. We can set `reason` through `DeletedState(reason)` but `createdAt` is a private field, the only thing that would be able to set that field is reflection, or via apt/compiler plugin we could change the bytecode to support a setter/constructor.

Further to that, I couldn't even test my serializer even if I wrote one:

```
val expects = DeletedState("reason") // no way to set createdAt
val json = "{\"reason\":\"testing\",\"createdAt\":\"2024-12-12T10:10:10Z\"}"
val actual = json.decodeFromString(json)
assertThat(actual).isEqualTo(expects) // fails
```

As the `DeletedState` would always use `SystemTime` to set `createdAt`, this is not generally the way to build public POJO's/API (vs internal only API) anymore, there should ideally be a constructor, or at least setter we can use.
See Stripe API and Java libs as a great examples.

For now I can fall back to adding [Moshi](https://github.com/square/moshi) as that will work with reading the Java classes using reflection and I can generate TypeAdapters for my classes. 
I would also recommend official support as it's more modern implementation that supports Kotlin.

Can we get extensible POJO's in the mean time to support the ~~Extensible.~~ part of the library description?

**Comment by auloin** [comment] 2024-08-23 08:32
@chrisjenx see https://github.com/jobrunr/jobrunr/tree/master/core/src/main/java/org/jobrunr/utils/mapper/jsonb for the implementation of JSON-B support.

**Comment by rdehuyss** [comment] 2024-08-23 17:40
Hi @chrisjenx - your correct and to be honest I completely forgot the reason why this was done to be honest. I think it was mostly to be sure that people are not creating / altering states themselves as it makes debugging GitHub issues a lot more difficult. Perhaps not a really valid reason but I really wanted to limit any risk to avoid unnecessary GH issues.

I'm thinking what to do with it.

**Comment by chrisjenx** [comment] 2024-08-23 17:43
@rdehuyss no worries, happy to submit a PR when ready, I might do a moshi one in the mean time, as thats a bit more Java/Kotlin friendly and much easier for people to move from GSON -> Moshi than kotlinx

**Comment by chrisjenx** [comment] 2024-08-25 17:47
OK some more feedback:

- there's a potential issue in your adapters, they don't truncate `Instant` down to seconds despite wanting an `ISO8601`. To fix change your adapters to use `instant.truncatedTo(ChronoUnit.SECONDS)` this will make sure you have no more than seconds.
- The validateAdapter test should change up the order, when writing a polymorphic adapter, you will fail the above due to the JobStates not getting serialized correctly, I would suggest changing the order to testing too:
```java
testUsePolymorphism(serializedJob);
testUseFieldsNotMethods(serializedJob);
testTimeFields(serializedJob);
```
Big to small when testing generally, helps hone down where the issue is, I found the first issue via not implementing the polymorphic serializer correctly.

Cheers!

**Comment by chrisjenx** [comment] 2024-08-25 19:36
Another issue:
```
JobRunrConfiguration() {
        this.jsonMapper = determineJsonMapper();
        this.jobMapper = new JobMapper(jsonMapper);
        this.jobDetailsGenerator = new CachingJobDetailsGenerator();
        this.jobFilters = new ArrayList<>();
    }
```

While you can pass in a custom mapper with the `useCustomMapper` you forcefully require that one of the other classpaths are enabled, couple of issues with this, you are validating up front before configuration has been provided, you should validate when you "build"/"start" with the provided config not before and require dependencies I don't need.

```
private static JsonMapper determineJsonMapper() {
        if (classExists("com.fasterxml.jackson.databind.ObjectMapper")) {
            return new JacksonJsonMapper();
        } else if (classExists("com.google.gson.Gson")) {
            return new GsonJsonMapper();
        } else if (classExists("jakarta.json.bind.JsonbBuilder")) {
            return new JsonbJsonMapper();
        } else {
            throw new JsonMapperException("No JsonMapper class is found. Make sure you have either Jackson, Gson or a JsonB compliant library available on your classpath");
        }
    }
```

**Comment by SIMULATAN** [comment] 2025-02-19 18:03
Hi everyone - good news, after more than 13 hours of painful programming, I managed to get everything running using kotlinx.serialization!

![13 hours on wakapi](https://github.com/user-attachments/assets/57432255-d5b5-434f-a740-ec608d714692)

It's a bit rough around the edges and probably still needs a bit of work until it is ready to be merged, but I'm asking everyone interested to try it out for themselves and report potential issues to get it out asap.

You can find the PR with instructions here: #1207
