### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by udoless** [jobrunr/jobrunr#688] opened 2023-02-13 11:20 UTC
### Runtime information
- __Timestamp__: 2022-08-26T08:57:48.781Z
- __Location__: BackgroundJobServer 200a376c-a466-422e-afe3-4ab2eed1ffe1
- __JobRunr Version__: 5.1.6
- __StorageProvider__: org.jobrunr.storage.sql.mariadb.MariaDbStorageProvider
- __Java Version__: 1.8.0_312
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: 218dfe4a-5d0d-4c0d-98cd-5c5b694fd717
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-23T09:31:28.052Z, lastHeartbeat: 2022-08-26T08:57:47.565Z)
- BackgroundJobServer id: e4881557-e77d-42ac-ad74-b5926b6aeb3b
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-23T09:31:29.494Z, lastHeartbeat: 2022-08-26T08:57:47.824Z)
- BackgroundJobServer id: 0f1c1868-049a-405e-b5fa-ddb02fe38080
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-23T09:31:30.091Z, lastHeartbeat: 2022-08-26T08:57:47.427Z)
- BackgroundJobServer id: 499cd71d-0775-4361-b86f-033075fd6c92
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-23T09:31:33.579Z, lastHeartbeat: 2022-08-26T08:57:43.306Z)
- BackgroundJobServer id: d2c727d2-8a74-4e78-aea7-2b310700d25c
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-23T09:31:37.558Z, lastHeartbeat: 2022-08-26T08:57:43.768Z)
- BackgroundJobServer id: 9f4533a6-ae1a-4eaa-a614-bbd1870a215f
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-23T09:31:53.425Z, lastHeartbeat: 2022-08-26T08:57:45.437Z)
- BackgroundJobServer id: 200a376c-a466-422e-afe3-4ab2eed1ffe1
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-23T09:31:54.812Z, lastHeartbeat: 2022-08-26T08:57:46.169Z)
- BackgroundJobServer id: 0d62fc8a-b7d1-4203-883b-ce801bd5d885
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-23T09:31:56.029Z, lastHeartbeat: 2022-08-26T08:57:45.869Z)
- BackgroundJobServer id: 6ab797fd-ccd1-4b2e-bcc8-577c17e07bdc
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-23T09:31:58.372Z, lastHeartbeat: 2022-08-26T08:57:44.899Z)
- BackgroundJobServer id: c704a4ad-f778-433b-bfe1-985fbff0146b
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-23T09:32:03.233Z, lastHeartbeat: 2022-08-26T08:57:40.663Z)

#### Concurrent modified jobs:
Job id: 96baa392-5280-48ad-b455-9bcac76e6b1e
	Local version: 450; Storage version: 451
	Local state: DELETED (at 2022-08-26T08:57:33.765Z) ← PROCESSING (updated at 2022-08-26T08:57:33.747Z on BackgroundJobServer 200a376c-a466-422e-afe3-4ab2eed1ffe1 and started at 2022-08-26T07:05:15.730Z) ← ENQUEUED (at 2022-08-26T07:05:14.915Z)
	Storage state: DELETED (at 2022-08-26T08:57:22.201Z) ← PROCESSING (updated at 2022-08-26T08:57:18.739Z on BackgroundJobServer 200a376c-a466-422e-afe3-4ab2eed1ffe1 and started at 2022-08-26T07:05:15.730Z) ← ENQUEUED (at 2022-08-26T07:05:14.915Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:212)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:92)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

### Runtime information
- __Timestamp__: 2022-08-26T09:09:41.797Z
- __Location__: BackgroundJobServer 6f92a593-1ff3-436c-8d92-a31e06161cf9
- __JobRunr Version__: 5.1.6
- __StorageProvider__: org.jobrunr.storage.sql.mariadb.MariaDbStorageProvider
- __Java Version__: 1.8.0_312
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: a755a519-b180-460b-b30a-36559a398827
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-26T08:59:08.056Z, lastHeartbeat: 2022-08-26T09:09:38.629Z)
- BackgroundJobServer id: 91d85b7f-bfb3-4b5b-af09-3bcf984b9eac
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-26T08:59:08.504Z, lastHeartbeat: 2022-08-26T09:09:38.851Z)
- BackgroundJobServer id: 6f92a593-1ff3-436c-8d92-a31e06161cf9
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-26T08:59:09.764Z, lastHeartbeat: 2022-08-26T09:09:40.133Z)
- BackgroundJobServer id: db283fe9-13ec-4fc6-925c-90cb3d012033
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-26T08:59:09.772Z, lastHeartbeat: 2022-08-26T09:09:40.130Z)
- BackgroundJobServer id: f054e6b0-8d75-4012-b29c-615ebc23bd0c
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-26T08:59:11.958Z, lastHeartbeat: 2022-08-26T09:09:27.198Z)
- BackgroundJobServer id: 5d79bb94-ea44-456d-958e-7362203c14c8
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-26T08:59:12.382Z, lastHeartbeat: 2022-08-26T09:09:27.635Z)
- BackgroundJobServer id: a7db14c3-ed0b-4055-8a49-1ad553d3bd70
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-26T08:59:13.868Z, lastHeartbeat: 2022-08-26T09:09:29.252Z)
- BackgroundJobServer id: 3bf8dd4d-0ef0-47d2-83fd-b23e68a1d185
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-26T08:59:21.775Z, lastHeartbeat: 2022-08-26T09:09:37.022Z)
- BackgroundJobServer id: 07cea233-ae29-4152-900d-0e48ba500bf2
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-26T08:59:24.807Z, lastHeartbeat: 2022-08-26T09:09:40.118Z)
- BackgroundJobServer id: e66a8a32-39c5-4248-92c3-b81f06bb74a4
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-26T08:59:27.328Z, lastHeartbeat: 2022-08-26T09:09:27.760Z)

#### Concurrent modified jobs:
Job id: f4f78e2b-4e17-44be-9d52-5324eaab9865
	Local version: 683; Storage version: 684
	Local state: DELETED (at 2022-08-26T09:09:26.778Z) ← PROCESSING (updated at 2022-08-26T09:09:26.762Z on BackgroundJobServer 6f92a593-1ff3-436c-8d92-a31e06161cf9 and started at 2022-08-26T09:00:25.838Z) ← ENQUEUED (at 2022-08-26T09:00:24.534Z) ← SCHEDULED (at 2022-08-26T09:00:09.365Z) ← FAILED (at 2022-08-26T09:00:09.360Z) ← PROCESSING (updated at 2022-08-26T08:58:40.386Z on BackgroundJobServer e4881557-e77d-42ac-ad74-b5926b6aeb3b and started at 2022-08-26T06:17:48.933Z)
	Storage state: DELETED (at 2022-08-26T09:09:18.131Z) ← PROCESSING (updated at 2022-08-26T09:09:11.744Z on BackgroundJobServer 6f92a593-1ff3-436c-8d92-a31e06161cf9 and started at 2022-08-26T09:00:25.838Z) ← ENQUEUED (at 2022-08-26T09:00:24.534Z) ← SCHEDULED (at 2022-08-26T09:00:09.365Z) ← FAILED (at 2022-08-26T09:00:09.360Z) ← PROCESSING (updated at 2022-08-26T08:58:40.386Z on BackgroundJobServer e4881557-e77d-42ac-ad74-b5926b6aeb3b and started at 2022-08-26T06:17:48.933Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:212)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:92)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by rdehuyss** [comment] 2023-02-13 16:51
Duplicate of #516

**Closed by rdehuyss** 2023-02-13 16:51 UTC
