### ISSUE TITLE
[Feature] Throw Exception when two recurring jobs have the same ID

### ISSUE THREAD

**Issue by marcphilippebeaujean-abertay** [jobrunr/jobrunr#251] opened 2021-11-05 14:24 UTC
When you have two recurring jobs defined that have the same ID, it causes problems in the Dashboard (it treats both like the same Job). The application builds just fine by default.

Ideally, there should be an exception when this happens or at least a warning. Am I missing something?

**Comment by rdehuyss** [comment] 2021-11-09 22:28
Hi,

Indeed, you are correct. You should not be able to create two recurring jobs with the same id.

Some questions:
- Which database are you using? 
- What is the name of your recurring job?

Normally, you cannot create two recurring jobs. For all Storage Providers, the name is treated as an ID. E.g. in SQL databases, the name will be inserted in the `ID` column which is a primary key so by definition cannot have duplicates. This is also for Mongo, Redis, ... .

**Comment by marcphilippebeaujean-abertay** [comment] 2021-11-13 08:59
Hi, I was using H2 in my local development environment. I was using the RecurringJob annotation as the way to schedule the job. Hope that helps!

**Comment by rdehuyss** [comment] 2021-11-29 22:49
I tried this and cannot reproduce it. If you still think this is an issue, please create a Github repo that reproduces this,

**Closed by rdehuyss** 2021-11-29 22:49 UTC
Labels: wontfix
