### ISSUE TITLE
[BUG] Scheduled Jobs not running anymore after upgrading to v6

### ISSUE THREAD

**Issue by gimmenowray** [jobrunr/jobrunr#684] opened 2023-02-09 00:46 UTC
### JobRunr Version

6.0.0

### JDK Version

Java SE 14

### Your SQL / NoSQL database

AWS RDS

### What happened?

migration from version 5.3.3 to version 6.0.0 all features are working with exception to scheduled recurring jobs which are in scheduled state with no progress to the next step (hang on scheduling state forever).

I am using background job to schedule a 30s recurring job.

had to downgrade in order to resolve the issue.

### How to reproduce?

BackgroundJob.<job> On a 30s interval 

### Relevant log output

```shell
As job is not triggered no logs are available
```

**Comment by rdehuyss** [comment] 2023-02-09 06:22
Closing this without answer as not following community guidelines:

> As this is an open-source project where we try to make a living from,
we kindly ask you to have a complete Github Personal Profile (Name and Company details or LinkedIn Profile).

I'm really sorry but I don't see why I should provide free support if you're not willing to provide me the above details. Please comment on this issue again as soon as your Github profile is complete. I will then reopen the issue.

**Comment by gimmenowray** [comment] 2023-02-09 08:22
Sorry, I will add all the required information. I was in a rush...

**Comment by gimmenowray** [comment] 2023-02-09 08:31
Done

**Comment by rdehuyss** [comment] 2023-02-09 11:04
I'm afraid I cannot reproduce this issue. The fact that you were able to downgrade also means that some migrations did not run as there are breaking database changes and migrations of scheduled jobs that need to happen after upgrading from v5 to v6.

### See screenshots: ###
#### Job scheduled with JobRunr 5.3.3 (see footer)
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/567842/217794650-1c0de2b7-8b3f-49f0-b8dd-6ba65c60629a.png">

#### Job still scheduled after upgrading to JobRunr 6.0.0  (see footer)
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/567842/217794807-1e0ab7c7-48c3-47be-af7a-24d482d53908.png">


#### Job succeeded with JobRunr 6.0.0
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/567842/217794922-67089e13-7205-4403-869b-a7ac5de0dbb7.png">

**Closed by rdehuyss** 2023-02-09 11:04 UTC
