### ISSUE TITLE
[Question] - How do you view your dashboard if a service using JobRunr is hosted on any cloud service like AWS?

### ISSUE THREAD

**Issue by ShubhajitM** [jobrunr/jobrunr#405] opened 2022-04-05 07:32 UTC
### Discussed in https://github.com/jobrunr/jobrunr/discussions/320

<div type='discussions-op-text'>

<sup>Originally posted by **sriharigr-threado** January 17, 2022</sup>
Hello,

I would like to know how I can monitor recurring jobs and scheduled jobs when a service using jobrunr is hosted on cloud.

Thanks</div>

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/100258269/161702076-ad5c9fe3-0956-40df-bfde-f82d3ea46067.png">

**Comment by ShubhajitM** [comment] 2022-04-05 07:33
Dashboard is throwing 401 in production

**Comment by ShubhajitM** [comment] 2022-04-05 07:35
@rdehuyss

**Comment by rdehuyss** [comment] 2022-04-05 07:42
Closing as this is a question and not a bug.

 I also don't like the way you interacted with me last time. If you want help, please consider taking a Pro subscription.

**Closed by rdehuyss** 2022-04-05 07:42 UTC

**Comment by ShubhajitM** [comment] 2022-04-05 09:02
If you want people to buy your subscription, then please don't make it open source. It is misleading the way you are doing things.
