### ISSUE TITLE
Reporting a "Severe JobRunr Exception" as requested by JobRunr UI

### ISSUE THREAD

**Issue by Mumeii** [jobrunr/jobrunr#1061] opened 2024-06-24 09:13 UTC
### Runtime information
- __Timestamp__: 2024-06-12T04:00:46.255621306Z
- __Location__: BackgroundJobServer 78f04c78-c23e-49af-a438-80855681152c
- __JobRunr Version__: 7.2.0
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 21.0.3
- __Is running from nested jar__: true
- __Is showing CpuAllocationNotification__: false

### Background Job Servers
- BackgroundJobServer id: 78f04c78-c23e-49af-a438-80855681152c
(workerPoolSize: 8, pollIntervalInSeconds: 30, firstHeartbeat: 2024-06-11T06:58:07.041329Z, lastHeartbeat: 2024-06-12T04:00:19.029254Z)

#### Concurrent modified jobs:
Job id: 01900a7c-ffbc-78b0-ae95-4a73937c3962
	Job Name: Pool - ComputeFamilyViewPartWeekRequest[pool=DASHBOARD]
	Job Signature: com.decathlon.stockcontrol.stockcontrolbatch.worker.job.jobrequesthandler.dashboard.ComputeFamilyViewPartWeekHandler.run(com.decathlon.stockcontrol.stockcontrolbatch.worker.job.jobrequest.dashboard.ComputeFamilyViewPartWeekRequest)
	Occurred at: 2024-06-12T04:00:46.255586917Z
	Local version: 3; Storage version: 4
	Local state: PROCESSING (updated at 2024-06-12T04:00:46.247966251Z on BackgroundJobServer 78f04c78-c23e-49af-a438-80855681152c and started at 2024-06-12T03:53:51.196794714Z) ← ENQUEUED (at 2024-06-12T03:28:03.255067240Z) ← SCHEDULED (at 2024-06-12T03:28:02.492311264Z)
	Storage state: FAILED (at 2024-06-12T03:56:07.389306666Z) ← PROCESSING (updated at 2024-06-12T03:53:51.196794714Z on BackgroundJobServer 78f04c78-c23e-49af-a438-80855681152c and started at 2024-06-12T03:53:51.196794714Z) ← ENQUEUED (at 2024-06-12T03:28:03.255067240Z) ← SCHEDULED (at 2024-06-12T03:28:02.492311264Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:69)
	at org.jobrunr.server.tasks.Task.convertAndProcessJobs(Task.java:55)
	at org.jobrunr.server.tasks.steward.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:17)
	at org.jobrunr.server.tasks.Task.run(Task.java:43)
	at org.jobrunr.server.JobHandler.lambda$run$0(JobHandler.java:35)
	at java.base/java.util.Arrays$ArrayList.forEach(Unknown Source)
	at org.jobrunr.server.JobHandler.run(JobHandler.java:35)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: 01900a7c-ffbc-78b0-ae95-4a73937c3962

## Concurrent modified jobs:
Job id: 01900a7c-ffbc-78b0-ae95-4a73937c3962
	Job Name: Pool - ComputeFamilyViewPartWeekRequest[pool=DASHBOARD]
	Job Signature: com.decathlon.stockcontrol.stockcontrolbatch.worker.job.jobrequesthandler.dashboard.ComputeFamilyViewPartWeekHandler.run(com.decathlon.stockcontrol.stockcontrolbatch.worker.job.jobrequest.dashboard.ComputeFamilyViewPartWeekRequest)
	Occurred at: 2024-06-12T04:00:46.255586917Z
	Local version: 3; Storage version: 4
	Local state: PROCESSING (updated at 2024-06-12T04:00:46.247966251Z on BackgroundJobServer 78f04c78-c23e-49af-a438-80855681152c and started at 2024-06-12T03:53:51.196794714Z) ← ENQUEUED (at 2024-06-12T03:28:03.255067240Z) ← SCHEDULED (at 2024-06-12T03:28:02.492311264Z)
	Storage state: FAILED (at 2024-06-12T03:56:07.389306666Z) ← PROCESSING (updated at 2024-06-12T03:53:51.196794714Z on BackgroundJobServer 78f04c78-c23e-49af-a438-80855681152c and started at 2024-06-12T03:53:51.196794714Z) ← ENQUEUED (at 2024-06-12T03:28:03.255067240Z) ← SCHEDULED (at 2024-06-12T03:28:02.492311264Z)

	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:64)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:67)
	... 12 more
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: 01900a7c-ffbc-78b0-ae95-4a73937c3962
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:216)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:309)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:190)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:63)
	... 12 more
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [1, 1, 1, 1, 1, 0]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:21)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:165)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:345)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:205)
	... 15 more

```

### Runtime information
- __Timestamp__: 2024-06-12T07:39:40.193256432Z
- __Location__: BackgroundJobServer 874108f8-1e4f-4e7f-b507-3a1f5d4dcc7b
- __JobRunr Version__: 7.2.0
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 21.0.3
- __Is running from nested jar__: true
- __Is showing CpuAllocationNotification__: false

### Background Job Servers
- BackgroundJobServer id: 874108f8-1e4f-4e7f-b507-3a1f5d4dcc7b
(workerPoolSize: 8, pollIntervalInSeconds: 30, firstHeartbeat: 2024-06-12T07:14:06.019533Z, lastHeartbeat: 2024-06-12T07:39:38.075997Z)

#### Concurrent modified jobs:
Job id: 01900a99-83e8-7e65-940f-a0fe92616a91
	Job Name: Store - TagcollectorAutoImpactRequest[store=Store[id=657, countryId=BE, timeZone=Europe/Brussels]]
	Job Signature: com.decathlon.stockcontrol.stockcontrolbatch.worker.job.jobrequesthandler.tagcollector.TagcollectorAutoImpactHandler.run(com.decathlon.stockcontrol.stockcontrolbatch.worker.job.jobrequest.tagcollector.TagcollectorAutoImpactRequest)
	Occurred at: 2024-06-12T07:39:40.193204692Z
	Local version: 3; Storage version: 4
	Local state: PROCESSING (updated at 2024-06-12T07:39:40.183507187Z on BackgroundJobServer 874108f8-1e4f-4e7f-b507-3a1f5d4dcc7b and started at 2024-06-12T07:33:55.913129017Z) ← ENQUEUED (at 2024-06-12T03:59:42.527672965Z) ← SCHEDULED (at 2024-06-12T03:59:11.336933708Z)
	Storage state: FAILED (at 2024-06-12T07:36:07.988861690Z) ← PROCESSING (updated at 2024-06-12T07:33:55.913129017Z on BackgroundJobServer 874108f8-1e4f-4e7f-b507-3a1f5d4dcc7b and started at 2024-06-12T07:33:55.913129017Z) ← ENQUEUED (at 2024-06-12T03:59:42.527672965Z) ← SCHEDULED (at 2024-06-12T03:59:11.336933708Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:69)
	at org.jobrunr.server.tasks.Task.convertAndProcessJobs(Task.java:55)
	at org.jobrunr.server.tasks.steward.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:17)
	at org.jobrunr.server.tasks.Task.run(Task.java:43)
	at org.jobrunr.server.JobHandler.lambda$run$0(JobHandler.java:35)
	at java.base/java.util.Arrays$ArrayList.forEach(Unknown Source)
	at org.jobrunr.server.JobHandler.run(JobHandler.java:35)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: 01900a99-83e8-7e65-940f-a0fe92616a91

## Concurrent modified jobs:
Job id: 01900a99-83e8-7e65-940f-a0fe92616a91
	Job Name: Store - TagcollectorAutoImpactRequest[store=Store[id=657, countryId=BE, timeZone=Europe/Brussels]]
	Job Signature: com.decathlon.stockcontrol.stockcontrolbatch.worker.job.jobrequesthandler.tagcollector.TagcollectorAutoImpactHandler.run(com.decathlon.stockcontrol.stockcontrolbatch.worker.job.jobrequest.tagcollector.TagcollectorAutoImpactRequest)
	Occurred at: 2024-06-12T07:39:40.193204692Z
	Local version: 3; Storage version: 4
	Local state: PROCESSING (updated at 2024-06-12T07:39:40.183507187Z on BackgroundJobServer 874108f8-1e4f-4e7f-b507-3a1f5d4dcc7b and started at 2024-06-12T07:33:55.913129017Z) ← ENQUEUED (at 2024-06-12T03:59:42.527672965Z) ← SCHEDULED (at 2024-06-12T03:59:11.336933708Z)
	Storage state: FAILED (at 2024-06-12T07:36:07.988861690Z) ← PROCESSING (updated at 2024-06-12T07:33:55.913129017Z on BackgroundJobServer 874108f8-1e4f-4e7f-b507-3a1f5d4dcc7b and started at 2024-06-12T07:33:55.913129017Z) ← ENQUEUED (at 2024-06-12T03:59:42.527672965Z) ← SCHEDULED (at 2024-06-12T03:59:11.336933708Z)

	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:64)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:67)
	... 12 more
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: 01900a99-83e8-7e65-940f-a0fe92616a91
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:216)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:309)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:190)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:63)
	... 12 more
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [1, 0, 1, 1, 1, 1, 1]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:21)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:165)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:345)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:205)
	... 15 more

```

### Runtime information
- __Timestamp__: 2024-06-12T08:40:46.473603228Z
- __Location__: BackgroundJobServer 25f714e0-317c-4fb1-b6f9-8396b6b16d23
- __JobRunr Version__: 7.2.0
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 21.0.3
- __Is running from nested jar__: true
- __Is showing CpuAllocationNotification__: false

### Background Job Servers
- BackgroundJobServer id: 25f714e0-317c-4fb1-b6f9-8396b6b16d23
(workerPoolSize: 8, pollIntervalInSeconds: 30, firstHeartbeat: 2024-06-12T08:07:11.594367Z, lastHeartbeat: 2024-06-12T08:40:43.620437Z)

#### Concurrent modified jobs:
Job id: 01900b83-3b57-7a6c-9fc7-569f4ca0f819
	Job Name: Store - TagcollectorAutoImpactRequest[store=Store[id=2094, countryId=NL, timeZone=Europe/Amsterdam]]
	Job Signature: com.decathlon.stockcontrol.stockcontrolbatch.worker.job.jobrequesthandler.tagcollector.TagcollectorAutoImpactHandler.run(com.decathlon.stockcontrol.stockcontrolbatch.worker.job.jobrequest.tagcollector.TagcollectorAutoImpactRequest)
	Occurred at: 2024-06-12T08:40:46.473530421Z
	Local version: 3; Storage version: 4
	Local state: PROCESSING (updated at 2024-06-12T08:40:46.439787513Z on BackgroundJobServer 25f714e0-317c-4fb1-b6f9-8396b6b16d23 and started at 2024-06-12T08:35:59.851638178Z) ← ENQUEUED (at 2024-06-12T08:14:59.493938329Z) ← SCHEDULED (at 2024-06-12T08:14:28.183125396Z)
	Storage state: FAILED (at 2024-06-12T08:38:14.131874824Z) ← PROCESSING (updated at 2024-06-12T08:35:59.851638178Z on BackgroundJobServer 25f714e0-317c-4fb1-b6f9-8396b6b16d23 and started at 2024-06-12T08:35:59.851638178Z) ← ENQUEUED (at 2024-06-12T08:14:59.493938329Z) ← SCHEDULED (at 2024-06-12T08:14:28.183125396Z)
Job id: 01900b83-3b57-7a6c-9fc7-569f4ca0f81a
	Job Name: Store - TagcollectorAutoImpactRequest[store=Store[id=2095, countryId=NL, timeZone=Europe/Amsterdam]]
	Job Signature: com.decathlon.stockcontrol.stockcontrolbatch.worker.job.jobrequesthandler.tagcollector.TagcollectorAutoImpactHandler.run(com.decathlon.stockcontrol.stockcontrolbatch.worker.job.jobrequest.tagcollector.TagcollectorAutoImpactRequest)
	Occurred at: 2024-06-12T08:40:46.473530421Z
	Local version: 3; Storage version: 4
	Local state: PROCESSING (updated at 2024-06-12T08:40:46.439791813Z on BackgroundJobServer 25f714e0-317c-4fb1-b6f9-8396b6b16d23 and started at 2024-06-12T08:35:59.869497216Z) ← ENQUEUED (at 2024-06-12T08:14:59.493938896Z) ← SCHEDULED (at 2024-06-12T08:14:28.183160425Z)
	Storage state: FAILED (at 2024-06-12T08:38:14.132296795Z) ← PROCESSING (updated at 2024-06-12T08:35:59.869497216Z on BackgroundJobServer 25f714e0-317c-4fb1-b6f9-8396b6b16d23 and started at 2024-06-12T08:35:59.869497216Z) ← ENQUEUED (at 2024-06-12T08:14:59.493938896Z) ← SCHEDULED (at 2024-06-12T08:14:28.183160425Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:69)
	at org.jobrunr.server.tasks.Task.convertAndProcessJobs(Task.java:55)
	at org.jobrunr.server.tasks.steward.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:17)
	at org.jobrunr.server.tasks.Task.run(Task.java:43)
	at org.jobrunr.server.JobHandler.lambda$run$0(JobHandler.java:35)
	at java.base/java.util.Arrays$ArrayList.forEach(Unknown Source)
	at org.jobrunr.server.JobHandler.run(JobHandler.java:35)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: 01900b83-3b57-7a6c-9fc7-569f4ca0f819, 01900b83-3b57-7a6c-9fc7-569f4ca0f81a

## Concurrent modified jobs:
Job id: 01900b83-3b57-7a6c-9fc7-569f4ca0f819
	Job Name: Store - TagcollectorAutoImpactRequest[store=Store[id=2094, countryId=NL, timeZone=Europe/Amsterdam]]
	Job Signature: com.decathlon.stockcontrol.stockcontrolbatch.worker.job.jobrequesthandler.tagcollector.TagcollectorAutoImpactHandler.run(com.decathlon.stockcontrol.stockcontrolbatch.worker.job.jobrequest.tagcollector.TagcollectorAutoImpactRequest)
	Occurred at: 2024-06-12T08:40:46.473530421Z
	Local version: 3; Storage version: 4
	Local state: PROCESSING (updated at 2024-06-12T08:40:46.439787513Z on BackgroundJobServer 25f714e0-317c-4fb1-b6f9-8396b6b16d23 and started at 2024-06-12T08:35:59.851638178Z) ← ENQUEUED (at 2024-06-12T08:14:59.493938329Z) ← SCHEDULED (at 2024-06-12T08:14:28.183125396Z)
	Storage state: FAILED (at 2024-06-12T08:38:14.131874824Z) ← PROCESSING (updated at 2024-06-12T08:35:59.851638178Z on BackgroundJobServer 25f714e0-317c-4fb1-b6f9-8396b6b16d23 and started at 2024-06-12T08:35:59.851638178Z) ← ENQUEUED (at 2024-06-12T08:14:59.493938329Z) ← SCHEDULED (at 2024-06-12T08:14:28.183125396Z)
Job id: 01900b83-3b57-7a6c-9fc7-569f4ca0f81a
	Job Name: Store - TagcollectorAutoImpactRequest[store=Store[id=2095, countryId=NL, timeZone=Europe/Amsterdam]]
	Job Signature: com.decathlon.stockcontrol.stockcontrolbatch.worker.job.jobrequesthandler.tagcollector.TagcollectorAutoImpactHandler.run(com.decathlon.stockcontrol.stockcontrolbatch.worker.job.jobrequest.tagcollector.TagcollectorAutoImpactRequest)
	Occurred at: 2024-06-12T08:40:46.473530421Z
	Local version: 3; Storage version: 4
	Local state: PROCESSING (updated at 2024-06-12T08:40:46.439791813Z on BackgroundJobServer 25f714e0-317c-4fb1-b6f9-8396b6b16d23 and started at 2024-06-12T08:35:59.869497216Z) ← ENQUEUED (at 2024-06-12T08:14:59.493938896Z) ← SCHEDULED (at 2024-06-12T08:14:28.183160425Z)
	Storage state: FAILED (at 2024-06-12T08:38:14.132296795Z) ← PROCESSING (updated at 2024-06-12T08:35:59.869497216Z on BackgroundJobServer 25f714e0-317c-4fb1-b6f9-8396b6b16d23 and started at 2024-06-12T08:35:59.869497216Z) ← ENQUEUED (at 2024-06-12T08:14:59.493938896Z) ← SCHEDULED (at 2024-06-12T08:14:28.183160425Z)

	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:64)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:67)
	... 12 more
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: 01900b83-3b57-7a6c-9fc7-569f4ca0f819, 01900b83-3b57-7a6c-9fc7-569f4ca0f81a
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:216)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:309)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:190)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:63)
	... 12 more
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [1, 1, 1, 0, 1, 1, 0, 1]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:21)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:165)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:345)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:205)
	... 15 more

```

**Comment by rdehuyss** [comment] 2024-06-24 09:53
Hi @Mumeii - can I ask what your database connection timeout is?

Normally, JobRunr saves a heartbeat for each job every 30 seconds (each `pollInterval`) yet for you we see periods of almost 7 minutes without this happening (the first exception: `2024-06-12T04:00:46.247966251Z` - `2024-06-12T03:53:51.196794714Z`).

Can you enable trace logging for the Job Server related tasks?

```
<logger name="org.jobrunr.server.tasks" level="TRACE"/>
```

**Comment by Mumeii** [comment] 2024-06-24 16:14
@rdehuyss : Hi
Would activating TRACE level on this package will enhance the pre-formated ascii doc message copied into the clipboard from the JobRunr UI ?

**Comment by Mumeii** [comment] 2024-06-24 16:19
Regarding our JobRunr DB timeout, we use a Hikari connexion pool to access it.

As we didn't configured anything fancy at this level, we rely on the default 30 seconds

**Comment by rdehuyss** [comment] 2024-06-24 17:07
> @rdehuyss : Hi Would activating TRACE level on this package will enhance the pre-formated ascii doc message copied into the clipboard from the JobRunr UI ?

No, we would need the logs from your logprovider (e.g. datadog, ... ).

**Comment by Mumeii** [comment] 2024-06-24 18:13
@rdehuyss :

Our log centralisation tool is also Datadog, and our OPS are very (very) reluctant to activate TRACE level logs historization to be honest 😋

How verbose are getting the logs from this package once this level is activated ?

In which proportion is it going to increase the log quantity ?
Will this only trace whenever a trouble such as the one reported occur ?

**Comment by rdehuyss** [comment] 2024-06-24 19:11
Well, it indeed will report quite a lot of logs every `pollIntervalInSeconds` (30 seconds in your case) but we need it to find the root cause of the issue. 

I would recommend trying to bump up the trace level locally so you have a good idea on what will be the impact. As it is trace log level, it will report all the time which we need to diagnose why certain steps are missing.

**Comment by rdehuyss** [comment] 2024-07-01 05:39
@Mumeii : can you provide us with the logs?

**Comment by rdehuyss** [comment] 2024-07-03 14:48
Duplicate of https://github.com/jobrunr/jobrunr-pro/issues/382.

**Closed by rdehuyss** 2024-07-03 14:48 UTC
